// API 类型定义模块导出

// 基础类型
export type {
  BaseApiResponse,
  ApiError,
  ResponseMeta,
  PaginationMeta,
  RateLimitMeta,
  RequestConfig,
  ResponseConfig,
  RequestInterceptor,
  ResponseInterceptor,
  CacheConfig,
  RetryConfig,
  TimeoutConfig,
  AuthConfig,
  RequestTransformer,
  ResponseTransformer,
  ApiClientConfig,
  EndpointConfig,
  WebSocketConfig,
  UploadConfig,
  DownloadConfig,
  BatchRequestConfig,
  RequestQueueConfig,
  HealthCheckConfig,
  MonitoringConfig,
  PerformanceMetrics,
  ApiVersionConfig,
  EnvironmentConfig,
  ApiClientInstance,
} from './common';

// 请求类型
export type {
  PaginationParams,
  DateRangeParams,
  SearchParams,
  LoginRequest,
  RegisterRequest,
  RefreshTokenRequest,
  UpdateProfileRequest,
  ChangePasswordRequest,
  CreatePaperRequest,
  UpdatePaperRequest,
  PaperListRequest,
  UploadPaperRequest,
  ParsePaperRequest,
  TranslatePaperRequest,
  CreateSectionRequest,
  UpdateSectionRequest,
  ReorderSectionsRequest,
  DeleteSectionRequest,
  CreateBlockRequest,
  UpdateBlockRequest,
  ReorderBlocksRequest,
  DeleteBlockRequest,
  CreateNoteRequest,
  UpdateNoteRequest,
  NoteListRequest,
  DeleteNoteRequest,
  TranslateTextRequest,
  TranslateBlockRequest,
  TranslateSectionRequest,
  UploadFileRequest,
  UploadImageRequest,
  UserListRequest,
  CreateUserRequest,
  UpdateUserRequest,
  DeleteUserRequest,
  UpdateSettingsRequest,
  NotificationSettings,
  PrivacySettings,
  EditorSettings,
  GlobalSearchRequest,
  AdvancedSearchRequest,
  ExportPaperRequest,
  ExportMultiplePapersRequest,
  BulkOperationRequest,
  CreateFeedbackRequest,
  UpdateFeedbackRequest,
  FeedbackListRequest,
} from './requests';

// 响应类型
export type {
  ApiResponse,
  ErrorDetail,
  ResponseMeta as ResponseMetaType,
  PaginationMeta as PaginationMetaType,
  RateLimitMeta as RateLimitMetaType,
  LoginResponse,
  RegisterResponse,
  RefreshTokenResponse,
  UserResponse,
  UserPreferences,
  NotificationPreferences,
  PrivacyPreferences,
  EditorPreferences,
  PaperResponse,
  Author,
  PaperMetadata,
  SectionResponse,
  BlockResponse,
  BlockType,
  BlockMetadata,
  Attachment,
  Collaborator,
  PaperPermissions,
  PaperListResponse,
  PaperStatsResponse,
  ActivityItem,
  NoteResponse,
  CommentResponse,
  NoteListResponse,
  TranslationResponse,
  BlockTranslationResponse,
  SectionTranslationResponse,
  PaperTranslationResponse,
  ParseJobResponse,
  ParseStage,
  ParseResultResponse,
  UploadResponse,
  ImageUploadResponse,
  DocumentUploadResponse,
  SearchResult,
  SearchResponse,
  SearchFacets,
  ExportJobResponse,
  BulkOperationResponse,
  BulkOperationResult,
  FeedbackResponse,
  SystemInfoResponse,
  HealthCheckResponse,
  HealthCheck,
  User,
} from './responses';

// 错误类型
export type {
  ValidationError,
  AuthenticationError,
  RateLimitError,
  NetworkError,
  ServerError,
  ClientError,
  ParseError,
  UploadError,
  DatabaseError,
  ExternalServiceError,
  BusinessLogicError,
  ErrorCodes,
  ErrorSeverity,
  ErrorCategory,
  ErrorContext,
  ErrorReport,
  ErrorRecoveryStrategy,
  ErrorHandlingConfig,
  ErrorNotification,
  ErrorMetrics,
  ErrorTrace,
} from './errors';